### ISSUE TITLE
Machine Learning Smartpens implementation using python

### ISSUE THREAD

**Issue by AryanSethi** [camicroscope/GSOC#6]
I propose to take up the ML SmartPens idea and implement it using python because I am experienced in python and computer vision. What is the procedure to follow?

**Comment by birm** [comment]
Hello @AryanSethi ,
This list is intended, at least now, as projects for [google summer of code](https://summerofcode.withgoogle.com/organizations/?sp-page=2#5022898667913216) so, if you're eligible for that program, I'd recommend applying the usual way.

If we don't end up running the smartpens projects with GSOC, then we may be able to work something else out.
I hope this helps!
