### ISSUE TITLE
Project suggestion 

### ISSUE THREAD

**Issue by Kareem-negm** [camicroscope/GSOC#7]
Hello caMicroscope team
 I have a project idea and aim to apply to do it with caMicroscope  in the GSoC22 so I want to discuss with the caMicroscope GSoC Director or potential mentor to see if the organization is interested in this project or not 
the project related to Microscope blood cell images with deep learning

**Comment by birm** [comment]
Please feel free to discuss in the slack channels for camicroscope :)
